version: "3.3"

services:
  db:
    container_name: library_db
    image: postgres:13
    restart: always
    env_file:
      - library_back/db.env
    ports:
    - "5432:5432"
    volumes:
      - var/lib/postegresql/data
    expose:
      - "5432"