version: "3.3"

services:
  db:
    container_name: library_db
    image: postgres:13
    restart: always
    env_file:
      - library_back/db.env
    ports:
    - "5432:5432"
    volumes:
      - var/lib/postegresql/data
    expose:
      - "5432"
  back:
    container_name: library_back
    build:
      context: ./library_back
      dockerfile: Dockerfile
    restart: always
    command: sh entrypoint.sh
    volumes:
      - .:/library_back
    ports:
      - "8000:8000"
    env_file:
      - library_back/db.env
    depends_on:
      - db